/* Emits supabase/seed.sql from the SAME deterministic generator the admin
   uses, so the local DB matches the in-memory demo exactly.
   Run:  npx tsx scripts/gen-seed.ts                                        */

import { writeFileSync } from "node:fs";
import { generateDataset } from "../src/admin/data/generate";
import { CATEGORIES, COLLECTIONS } from "../src/data/catalog";
import { CATEGORY_CODE } from "../src/admin/data/sku";

const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const arr = (xs: string[] | undefined) =>
  !xs?.length ? "'{}'" : `ARRAY[${xs.map(q).join(",")}]::text[]`;

/** batch multi-row INSERTs — one statement per 500 rows beats 7k round trips */
function batched(table: string, cols: string[], rows: string[][], size = 500): string {
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += size) {
    const chunk = rows.slice(i, i + size);
    out.push(
      `insert into ${table} (${cols.join(", ")}) values\n` +
        chunk.map((r) => `  (${r.join(", ")})`).join(",\n") +
        ";"
    );
  }
  return out.join("\n\n");
}

const { styles, customers, orders, skuCount } = generateDataset();

const parts: string[] = [
  `-- GENERATED by scripts/gen-seed.ts — do not edit by hand.`,
  `-- ${styles.length} styles · ${skuCount} SKUs · ${orders.length} orders · ${customers.length} customers`,
  ``,
  `begin;`,
  ``,
];

/* ---- taxonomy ---- */
parts.push(
  batched(
    "public.categories",
    ["id", "label", "sku_prefix", "sort"],
    CATEGORIES.map((c, i) => [q(c.id), q(c.label), q(CATEGORY_CODE[c.id]), String(i)])
  )
);
parts.push(
  batched(
    "public.collections",
    ["id", "label", "season", "note", "image", "sort"],
    COLLECTIONS.map((c, i) => [q(c.id), q(c.label), q(c.season), q(c.note), q(c.image), String(i)])
  )
);

/* ---- size rules ---- */
const BASE = [
  ["XS", 76, 80, 58, 62, 82, 86],
  ["S", 81, 85, 63, 67, 87, 91],
  ["M", 86, 90, 68, 72, 92, 96],
  ["L", 91, 96, 73, 78, 97, 102],
  ["XL", 97, 103, 79, 85, 103, 109],
  ["2XL", 104, 110, 86, 92, 110, 116],
] as const;
const BODY = [
  ["hourglass", "Hourglass", "Balanced bust & hip with a defined waist.", "Size to the bust; nip the waist. Mermaid & bias cuts shine."],
  ["pear", "Pear", "Hip wider than bust.", "Size to the hip, then tailor the bodice down 1 size."],
  ["apple", "Apple", "Fuller midsection, slimmer legs.", "Size to the bust; empire & wrap release the waist."],
  ["rectangle", "Rectangle", "Bust, waist, hip fairly even.", "Size to the bust; ruching & belts add curve."],
  ["inverted-triangle", "Inverted triangle", "Shoulder/bust wider than hip.", "Size to the bust; A-line & ball-gown balance the hip."],
] as const;

parts.push(
  batched(
    "public.body_rule_meta",
    ["body_type", "label", "guidance", "ease_note"],
    BODY.map((b) => [`${q(b[0])}::public.body_type`, q(b[1]), q(b[2]), q(b[3])])
  )
);
parts.push(
  batched(
    "public.size_rules",
    ["body_type", "size", "bust_min", "bust_max", "waist_min", "waist_max", "hip_min", "hip_max"],
    BODY.flatMap((b) =>
      BASE.map((r) => [
        `${q(b[0])}::public.body_type`, q(r[0]),
        String(r[1]), String(r[2]), String(r[3]), String(r[4]), String(r[5]), String(r[6]),
      ])
    )
  )
);

/* ---- styles ---- */
parts.push(
  batched(
    "public.styles",
    ["id", "style_code", "serial", "name", "category_id", "collection_id", "silhouette",
     "occasion", "price", "material", "body_type", "status", "images",
     "units_sold", "views", "returns", "created_at"],
    styles.map((s) => [
      `gen_random_uuid()`, q(s.styleCode), String(s.serial), q(s.name), q(s.category),
      q(s.collection), q(s.silhouette), q(s.occasion), String(s.price), q(s.material),
      `${q(s.bodyType)}::public.body_type`, `${q(s.status)}::public.style_status`, arr(s.images),
      String(s.unitsSold), String(s.views), String(s.returns), q(s.createdAt),
    ])
  )
);

/* ---- variants (resolve style_id by style_code) ---- */
parts.push(
  batched(
    "public.variants",
    ["sku", "style_id", "color_name", "color_hex", "size", "stock", "reserved", "barcode", "price_override"],
    styles.flatMap((s) =>
      s.variants.map((v) => [
        q(v.sku),
        `(select id from public.styles where style_code = ${q(s.styleCode)})`,
        q(v.colorName), q(v.colorHex), q(v.size),
        String(v.stock), String(v.reserved), q(v.barcode),
        v.priceOverride ? String(v.priceOverride) : "NULL",
      ])
    )
  )
);

/* ---- customers ---- */
parts.push(
  batched(
    "public.customers",
    ["id", "name", "email", "city", "segment", "body_type", "orders_count", "ltv", "joined"],
    customers.map((c) => [
      `gen_random_uuid()`, q(c.name), q(c.email), q(c.city),
      `${q(c.segment)}::public.segment`, `${q(c.bodyType)}::public.body_type`,
      String(c.orders), String(c.ltv), q(c.joined),
    ])
  )
);

/* ---- orders (resolve customer_id by email) ---- */
const emailOf = new Map(customers.map((c) => [c.id, c.email]));
parts.push(
  batched(
    "public.orders",
    ["id", "customer_id", "status", "channel", "city", "total", "placed_at"],
    orders.map((o) => [
      q(o.id),
      `(select id from public.customers where email = ${q(emailOf.get(o.customerId)!)})`,
      `${q(o.status)}::public.order_status`, `${q(o.channel)}::public.order_channel`,
      q(o.city), String(o.total), q(o.date),
    ])
  )
);

/* ---- order items ---- */
parts.push(
  batched(
    "public.order_items",
    ["order_id", "sku", "name", "size", "color", "qty", "price"],
    orders.flatMap((o) =>
      o.items.map((i) => [
        q(o.id), q(i.sku), q(i.styleName), q(i.size), q(i.color), String(i.qty), String(i.price),
      ])
    )
  )
);

parts.push(``, `commit;`, ``, `analyze;`, ``);

writeFileSync("supabase/seed.sql", parts.join("\n\n"));
console.log(
  `seed.sql written — ${styles.length} styles, ${skuCount} SKUs, ${orders.length} orders, ${customers.length} customers`
);
